export const sliderData = [
  {
    title: "First Game",
    image: require("/Users/roygutter/Desktop/Full-Stuck/projects/ReactNativeApp/RoysPart/src/assets/images/sliderData1.jpeg"),
  },
  {
    title: "Seacond Game",
    image: require("/Users/roygutter/Desktop/Full-Stuck/projects/ReactNativeApp/RoysPart/src/assets/images/sliderData2.webp"),
  },
  {
    title: "Third Game",
    image: require("/Users/roygutter/Desktop/Full-Stuck/projects/ReactNativeApp/RoysPart/src/assets/images/sliderData3.jpeg"),
  },
];

export const CommunityGames = [
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "5 on 5",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "1",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "2",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
];
export const PremiumGames = [
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    typeOfGame: "5 on 5",
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "1",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "2",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
];
