export const sliderData = [
  
   ("../images/slideroption1.jpeg"),
  ,
 
   ("../images/slideroption2.jpg"),
 
  
   ("../images/slideroption3.jpeg"),

];

export const CommunityGames = [
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "5 on 5",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "1",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "2",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "Sporteck Tel-Aviv",
    players: 10,
    typeOfGame: "3 on 3",
    ages: "any age",
    level: "begginers",
    price: "free",
    id: "3",
  },
];
export const PremiumGames = [
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    typeOfGame: "5 on 5",
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "1",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "2",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
  {
    startTime: "19:00",
    endTime: "21:00",
    date: "06/03/2022",
    location: "MidTownTlv",
    players: 10,
    ages: "any age",
    level: "begginers",
    price: "50₪",
    id: "14",
  },
];
